service: serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: '{proxy+}'
          method: ANY

custom:
  serverless-offline:
    noPrependStageInUrl: true