service: serverless-techchallenge

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  environment:
    NODE_ENV: ${self:provider.stage}
    DYNAMODB_TABLE: Personas
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          path: personas
          method: post
      - http:
          path: personas
          method: get
      - http:
          path: personas/{id}
          method: get
      - http:
          path: swapi/personas
          method: get
      - http:
          path: swapi/persona/{id}
          method: get

custom:
  serverless-offline:
    noPrependStageInUrl: true

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
