service: serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  environment:
    NODE_ENV: ${self:provider.stage}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          path: swapi/personas
          method: get
      - http:
          path: swapi/persona/{id}
          method: get

custom:
  serverless-offline:
    noPrependStageInUrl: true
